apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - config-map.yaml
  - external-secret.yaml
  - deployment.yaml
  - pod-disruption-budget.yaml
  - horizontal-pod-autoscaler.yaml
  - service.yaml
  - http-route.yaml
