apiVersion: v1
kind: ServiceAccount
metadata:
  name: nestjs-boilerplate-dev-app
  namespace: nestjs-boilerplate-dev-workload
  labels:
    app.kubernetes.io/name: nestjs-boilerplate-dev-app
    app.kubernetes.io/part-of: nestjs-boilerplate
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: dev
automountServiceAccountToken: true
