apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  template:
    metadata:
      labels:
        workload: app
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - key: workload
          value: app
          effect: NoSchedule
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
