apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: 2.64.0
    helm:
      releaseName: aws-ebs-csi-driver
      values: |
        controller:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::741437278375:role/nestjs-boilerplate-dev-ebs-csi-role
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
