apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-public-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '15'
spec:
  project: default
  source:
    repoURL: https://github.com/mikemajesty/nestjs-microservice-boilerplate-api.git
    targetRevision: master
    path: gitops/cluster/public-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
