apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/mikemajesty/nestjs-microservice-boilerplate-api.git
    targetRevision: master
    path: gitops/addons/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
