apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '26'
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.15
    helm:
      releaseName: grafana
      values: |
        fullnameOverride: grafana

        service:
          type: ClusterIP
          port: 3000

        persistence:
          enabled: true
          type: pvc
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          size: 10Gi

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.monitoring.svc.cluster.local:9090
                isDefault: true
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.monitoring.svc.cluster.local:3100
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
