apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  source:
    repoURL: https://github.com/aws/karpenter-provider-aws.git
    targetRevision: v1.14.0
    path: pkg/apis/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
