apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-manifest
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/mikemajesty/nestjs-microservice-boilerplate-api
    targetRevision: master
    path: gitops/addons/otel-collector
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
