apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/mikemajesty/nestjs-microservice-boilerplate-api.git
    targetRevision: master
    path: gitops/apps/smoke-app
  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-boilerplate-dev-workload
  syncPolicy:
    syncOptions:
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
