apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-gateway-tls
  namespace: envoy-gateway-system
spec:
  secretName: internal-gateway-tls
  # Change this issuerRef when using an existing company CA.
  issuerRef:
    name: internal-ca-cluster-issuer
    kind: ClusterIssuer
  commonName: api.boilerplate.internal
  dnsNames:
    - api.boilerplate.internal
