apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - self-signed-cluster-issuer.yaml
  - internal-root-ca-certificate.yaml
  - internal-ca-cluster-issuer.yaml
  - internal-gateway-certificate.yaml
