apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nestjs-boilerplate-dev-smoke-app
  namespace: nestjs-boilerplate-dev-workload
  labels:
    app.kubernetes.io/name: nestjs-boilerplate-dev-smoke-app
    app.kubernetes.io/part-of: nestjs-boilerplate
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/environment: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nestjs-boilerplate-dev-smoke-app-runtime
    creationPolicy: Owner
  data:
    - secretKey: SMOKE_SECRET_MESSAGE
      remoteRef:
        key: nestjs-boilerplate/dev/smoke-app
        property: SMOKE_SECRET_MESSAGE
