apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envoy-config
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: envoy-config
    creationPolicy: Owner
  data:
    - secretKey: nlb-security-group-id
      remoteRef:
        key: /nestjs-boilerplate/dev/infra/envoy-nlb-sg-id
